import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import Layout from "../components/Layout";
import {
    postFilePaths,
    POSTS_PATH,
    noteFilePaths,
    NOTES_PATH,
} from "../utils/mdxUtils";

export default function Index({ posts, notes }) {
    return (
        <Layout>
            <h1>Home Page</h1>
            <p>
                Click the link below to navigate to a page generated by{" "}
                <code>next-mdx-remote</code>.
            </p>
            <ul>
                {posts.map((post) => (
                    <li key={post.filePath}>
                        <Link
                            as={`/posts/${post.filePath.replace(
                                /\.mdx?$/,
                                ""
                            )}`}
                            href={`/posts/[slug]`}
                        >
                            <a>{post.data.title}</a>
                        </Link>
                    </li>
                ))}
            </ul>
            <ul>
                {notes.map((note) => (
                    <li key={note.filePath}>
                        <Link
                            as={`/notes/${note.filePath.replace(
                                /\.mdx?$/,
                                ""
                            )}`}
                            href={`/notes/[slug]`}
                        >
                            <a>{note.data.title}</a>
                        </Link>
                    </li>
                ))}
            </ul>
        </Layout>
    );
}

export function getStaticProps() {
    const posts = postFilePaths.map((filePath) => {
        const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath,
        };
    });

    const notes = noteFilePaths.map((filePath) => {
        const source = fs.readFileSync(path.join(NOTES_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath,
        };
    });

    return { props: { posts, notes } };
}
