import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import Layout from "../components/Layout";
import {
    essayFilePaths,
    ESSAYS_PATH,
    noteFilePaths,
    NOTES_PATH,
} from "../utils/mdxUtils";

export default function Index({ essays, notes }) {
    return (
        <Layout>
            <h1>Home Page</h1>
            <p>
                Click the link below to navigate to a page generated by{" "}
                <code>next-mdx-remote</code>.
            </p>
            <ul>
                {essays.map((essay) => (
                    <li key={essay.filePath}>
                        <Link
                            as={`/${essay.filePath.replace(/\.mdx?$/, "")}`}
                            href={`/[slug]`}
                        >
                            <a>{essay.data.title}</a>
                        </Link>
                    </li>
                ))}
            </ul>
            <ul>
                {notes.map((note) => (
                    <li key={note.filePath}>
                        <Link
                            as={`/${note.filePath.replace(/\.mdx?$/, "")}`}
                            href={`/[slug]`}
                        >
                            <a>{note.data.title}</a>
                        </Link>
                    </li>
                ))}
            </ul>
        </Layout>
    );
}

export function getStaticProps() {
    const essays = essayFilePaths.map((filePath) => {
        const source = fs.readFileSync(path.join(ESSAYS_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath,
        };
    });

    const notes = noteFilePaths.map((filePath) => {
        const source = fs.readFileSync(path.join(NOTES_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath,
        };
    });

    return { props: { essays, notes } };
}
